In [1]:
import numpy as np
import pandas as pd

/Users/Olivier/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))


### Riddle

In [2]:
data= """
8809=6
7111=0
2172=0
6666=4
1111=0
3213=0
7662=2
9313=1
0000=4
2222=0
3333=0
5555=0
8193=3
8096=5
7777=0
9999=4
7756=1
6855=3
9881=5
5531=0
2581=?
"""

### Indication: This problem can be solved by a pre schooler.

A preschooler does not know anything but a sum.  
So let us assume that the riddle is about mapping each digit to a unique key value.  

We tranform each equation into a frequency equation.  
for example the first one is  
$$f_0*1+f_8*2+f_9*1 = 6$$

Then we search the 'best' solution $(f_i)$ using the least square algo.

In [3]:
def lhs_to_freq(lhs):
    unique, counts = np.unique(lhs, return_counts=True)
    freq = np.zeros(10, dtype=np.int)
    freq[unique] = counts
    return freq

def get_freq_from_eq(eq):
    lhs = np.array(list(eq.split('=')[0])).astype(np.int)
    return lhs_to_freq(lhs)

def get_res_from_eq(eq):
    rhs = int(eq.split('=')[1])
    return rhs

A = np.array(map(get_freq_from_eq, data.split()[:-1]))
b = np.array(map(get_res_from_eq, data.split()[:-1]))

print 'System to solve:\tA x = b\nwith'
print 'A =\n{}'.format(A)
print 'b =\n{}'.format(b)

# candidate solution
s = np.round(np.linalg.lstsq(A, b)[0]).astype(np.int)
print '\nCandidation solution:\nDigit\t{}\nValue\t{}'.format(np.arange(10), s)
print '\nIs candidate solution valid ? i.e. A s == b ?\n{}'.format(np.all(np.dot(A, s)==b))

# answer
print '\nConclusion\n2581 = {}'.format(np.sum(s * lhs_to_freq([2, 5, 8, 1])))

System to solve:	A x = b
with
A =
[[1 0 0 0 0 0 0 0 2 1]
 [0 3 0 0 0 0 0 1 0 0]
 [0 1 2 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 4 0 0 0]
 [0 4 0 0 0 0 0 0 0 0]
 [0 1 1 2 0 0 0 0 0 0]
 [0 0 1 0 0 0 2 1 0 0]
 [0 1 0 2 0 0 0 0 0 1]
 [4 0 0 0 0 0 0 0 0 0]
 [0 0 4 0 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 1 0 1 0 0 0 0 1 1]
 [1 0 0 0 0 0 1 0 1 1]
 [0 0 0 0 0 0 0 4 0 0]
 [0 0 0 0 0 0 0 0 0 4]
 [0 0 0 0 0 1 1 2 0 0]
 [0 0 0 0 0 2 1 0 1 0]
 [0 1 0 0 0 0 0 0 2 1]
 [0 1 0 1 0 2 0 0 0 0]]
b =
[6 0 0 4 0 0 2 1 4 0 0 0 3 5 0 4 1 3 5 0]

Candidation solution:
Digit	[0 1 2 3 4 5 6 7 8 9]
Value	[1 0 0 0 0 0 1 0 2 1]

Is candidate solution valid ? i.e. A s == b ?
True

Conclusion
2581 = 2
